name: Terraform Format Check and Validate Workflow.

on:
  pull_request:
    branches:
      - main

jobs:
  terraform-format:
    name: Terraform format check
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check Terraform formatting
      uses: dflook/terraform-fmt-check@v1
      with:
        path: terraform

    
  terraform-validate:
    name: Terraform validation
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Validate Terraform modules
      uses: dflook/terraform-validate@v1
      with:
        path: terraform